/**
 * NEURON IIoT System for Industry 4.0
 * Copyright (C) 2020-2022 EMQ Technologies Co., Ltd All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 **/

/*
 * DO NOT EDIT THIS FILE MANUALLY!
 * It was automatically generated by `json-autotype`.
 */

#include <stdlib.h>
#include <string.h>

#include "json/json.h"

#include "persist/json/persist_json_plugin.h"

/**
 * @brief 对包含插件请求信息的 JSON 字符串进行解码
 *
 * 该函数接收一个包含 JSON 格式插件请求信息的字符串，将其解码为 `neu_json_plugin_req_t` 结构体。
 * 解码过程包括解析 JSON 数据，提取插件数量和每个插件的信息，并将这些信息存储在分配的结构体中。
 *
 * @param buf 指向包含 JSON 格式插件请求信息的字符串的指针。该字符串应符合特定的 JSON 结构，
 *            包含一个名为 "plugins" 的数组，数组元素为插件相关信息。
 * @param result 一个指向指针的指针，用于存储解码后得到的 `neu_json_plugin_req_t` 结构体的地址。
 *               如果解码成功，该指针将指向分配的 `neu_json_plugin_req_t` 结构体；如果失败，该指针值不变。
 *
 * @return 解码操作的结果状态码：
 *         - 0：解码成功，`*result` 指向有效的 `neu_json_plugin_req_t` 结构体。
 *         - -1：解码失败，可能是由于内存分配失败、JSON 解析错误或数据格式不符合要求等原因。
 *
 * @note 调用该函数后，调用者有责任在不再使用 `*result` 指向的结构体时，释放其占用的内存，
 *       以避免内存泄漏。
 */
int neu_json_decode_plugin_req(char *buf, neu_json_plugin_req_t **result)
{
    int                    ret      = 0;
    void *                 json_obj = NULL;
    neu_json_plugin_req_t *req      = calloc(1, sizeof(neu_json_plugin_req_t));
    if (req == NULL) {
        return -1;
    }

    json_obj = neu_json_decode_new(buf);

    req->n_plugin = neu_json_decode_array_size_by_json(json_obj, "plugins");
    if (req->n_plugin <= 0) {
        goto decode_fail;
    }

    // 为存储 char* 类型指针的数组分配了内存。指针的大小在32位系统上是4 字节，在64位系统上是8字节
    req->plugins = calloc(req->n_plugin, sizeof(neu_json_plugin_req_plugin_t));
    neu_json_plugin_req_plugin_t *p_plugin = req->plugins;
    for (int i = 0; i < req->n_plugin; i++) {
        neu_json_elem_t plugin_elems[] = { {
            .name = NULL,
            .t    = NEU_JSON_STR,
        } };
        ret = neu_json_decode_array_by_json(json_obj, "plugins", i,
                                            NEU_JSON_ELEM_SIZE(plugin_elems),
                                            plugin_elems);
        if (ret != 0) {
            goto decode_fail;
        }

        *p_plugin = plugin_elems[0].v.val_str;
        p_plugin++;
    }

    *result = req;
    goto decode_exit;

decode_fail:
    if (req->plugins != NULL) {
        free(req->plugins);
    }
    if (req != NULL) {
        free(req);
    }
    ret = -1;

decode_exit:
    if (json_obj != NULL) {
        neu_json_decode_free(json_obj);
    }
    return ret;
}

void neu_json_decode_plugin_req_free(neu_json_plugin_req_t *req)
{

    neu_json_plugin_req_plugin_t *p_plugin = req->plugins;
    for (int i = 0; i < req->n_plugin; i++) {
        free(*p_plugin);
        p_plugin++;
    }

    free(req->plugins);

    free(req);
}

int neu_json_encode_plugin_resp(void *json_object, void *param)
{
    int                     ret  = 0;
    neu_json_plugin_resp_t *resp = (neu_json_plugin_resp_t *) param;

    void *                         plugin_array = neu_json_array();
    neu_json_plugin_resp_plugin_t *p_plugin     = resp->plugins;
    for (int i = 0; i < resp->n_plugin; i++) {
        neu_json_elem_t plugin_elems[] = { {
            .name      = NULL,
            .t         = NEU_JSON_STR,
            .v.val_str = *p_plugin,
        } };
        plugin_array                   = neu_json_encode_array_value(
            plugin_array, plugin_elems, NEU_JSON_ELEM_SIZE(plugin_elems));
        p_plugin++;
    }

    neu_json_elem_t resp_elems[] = { {
        .name         = "plugins",
        .t            = NEU_JSON_OBJECT,
        .v.val_object = plugin_array,
    } };
    ret = neu_json_encode_field(json_object, resp_elems,
                                NEU_JSON_ELEM_SIZE(resp_elems));

    return ret;
}
